spring.application.name=StreamGestor
server.port=8082

# Base de datos H2 para ejecutar el proyecto sin instalar MySQL.
spring.datasource.url=jdbc:h2:mem:streamgestor_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
